spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sw
    username: postgres
    password: postgres
  jpa:
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: create  # or create-drop for testing, but be cautious in production
          show_sql: true
          format_sql: true
